### ISSUE TITLE
Building from repo fails

### ISSUE THREAD

**Issue by axal90** [justindujardin/ng2-material#209]
Windows 10
clone -> npm install -> grunt serve

For some reason duplicate typings files are created.
there is the `typings/main/ambient/node/node.d.ts`
it also creates `typings/main/ambient/node/index.d.ts`
wich is refrenced in "typings/main.d.ts"

```
     /// <reference path="main/ambient/jasmine/index.d.ts" />
     /// <reference path="main/ambient/jasmine/jasmine.d.ts" />
     /// <reference path="main/ambient/node/index.d.ts" />
     /// <reference path="main/ambient/node/node.d.ts" />
```
This causes a bunch of errors like this:
`typings/main/ambient/jasmine/index.d.ts(74,9): error TS2300: Duplicate identifier 'length'.`

removing any refrence to `typings/*/*/*/index.d.ts` from `typings/main.d.ts` and `typings/browser.d.ts` fixes it but would be nice if that wasnt an issue.

I am kind of guessing that this is something to do with my setup but as of yet I am unable to find the cause.

**Comment by steve-farr** [comment]
This is due to the change from tsd (which uses say node.d.ts) to typings (which names files index.d.ts).

The temporary fix is quite simple. 

1) Delete the existing `typings` folder
2) Run (assuming you've got typings installed globally):
```
typings install
```
Then is should build without the duplicate error. 

(Someone needs to do this and then commit the changes.)

**Comment by axal90** [comment]
@steve-farr Thank you for pointing this out.

The project is not yet dependet on typings.
Should we introduce that dependency?

**Comment by Gregcop1** [comment]
Yes, we should. And maybe we should remove current definitions from repo and add a "npm post-install script" to install them.

**Comment by justindujardin** [comment]
I'm open to changing this, but it was intentional to allow installation in more restrictive network environments (where an npm registry might be present and accessible, but typings might not.)

https://github.com/justindujardin/ng2-material/issues/74

If we change this we'd want to make sure that we strip out the postinstall script in the `dist/package.json` file before publishing.  I think that would satisfy all needs.

**Comment by justindujardin** [comment]
This should be fixed with https://github.com/justindujardin/ng2-material/commit/772fab4ba242718f00c2b2a4bee75cef2b5e9e61
