### ISSUE TITLE
Serve after RC

### ISSUE THREAD

**Issue by Gregcop1** [justindujardin/ng2-material#236]
Hi @justindujardin. I update my PR about MdPagination but after the RC friendly build, I can't see exemple site anymore. Did I miss something ? Is the documentation still ok ?

**Comment by justindujardin** [comment]
the example site is moved to modules/site and uses angular-cli to run. It's still a little strange because you need to run `grunt develop` from the root of the repo and then run `ng serve` from `modules/site`.  

Does this not work for you?

**Comment by Gregcop1** [comment]
Finally it works. but a `npm install` is required in `modules/site` then `ng serve` and finally the `grunt develop`
We definitely need to write documentation about that and seek for a simple to do the same (maybe merging the two `package.json`

**Comment by axal90** [comment]
is it possible to make a script that does all that from project root? 
something like:
```"scripts": {
    "server": "grunt develop, cd modules/site, npm install, ng serve",
}```
so you just have to type `npm run server` to get it all up and running
maybe also include setting up required linking to use local version of ng2-material

**Comment by Gregcop1** [comment]
I investigate a bit to get something working and it appears it's very unstable ATM. 
First grunt build
Then goto to modules/site and npm install
Finally ng serve

Without this, some fonts are missing.

IMO we have to merge the two package.json in one, revamp the grunt task to prepare the sample site on each build and expose some news scripts via npm

**Comment by ollwenjones** [comment]
@axal90 setting up pre and post NPM task scripts should be able to handle it, or there are tools like parallel shell.

Running a combo of Angular CLI and a fairly long/complex Grunt setup seems like a maintenance problem long term though. Might be better to switch to Angular CLI altogether (if it's required because of Material 2) or something else that can do everything we need (like webpack)

**Comment by justindujardin** [comment]
Long-term I'd like to move to angular-cli because it uses Broccoli and is maintained by the angular team. I'm still trying to conceptualize how all the grunt tasks would carry over. There are a few things that grunt does which are important:

 - Builds the metadata files about the components and their examples for the site.
 - Builds a proper dist/ path that contains a publishable npm package
 - Deploys and bumps release versions, updating the changelog and publishing to npm
 - Maps all of the saucelabs karma coverage results into a single report to send to coveralls.io

I don't know if merging the `package.json` files is a good idea. They allow us to have different package dependencies for the core library and for an app that uses it, make sure the examples import in the same way an end-user would, and the separate folder with it's own `package.json` makes it easy for someone to reference as a starting point.

For now I would suggest we bandage the problem by making sure the documentation explains how to run the site (something very few people do right now.) Perhaps using install scripts as @ollwenjones suggests to generate the missing site files when you first install the root project?

**Comment by ollwenjones** [comment]
```bash
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'C:\devel\repos\ng2-material\justindujardin\modules\site\tmp\broccoli_type_script_compiler-cache_path-t23vgUn9.tmp\src\app\+components\components.component.spec.js.map' -> 'C:\devel\repos\ng2-material\justindujardin\modules\site\tmp\broccoli_type_script_compiler-output_path-XOCy6xVt.tmp\src\app\+components\components.component.spec.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\devel\repos\ng2-material\justindujardin\modules\site\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by ollwenjones** [comment]
Above error was due to being on Windows, on a console without "Administrative Privileges." With privileges it runs fine. Relates to Angular-CLI issue [#641](https://github.com/angular/angular-cli/issues/641) - which "should be fixed in beta.6"
