### ISSUE TITLE
statement of goals, plans with ng2-material

### ISSUE THREAD

**Issue by maku** [justindujardin/ng2-material#6]
It would be useful when a little description of the library is available:

e.g. I am curious about the goal? Is this lib a placeholder until the "official" angular material implementation is ready for ng2 (syntax is very similar to angular material).  Or do you plan to continue this lib?

**Comment by NathanWalker** [comment]
^ I'm curious on the above as well.

**Comment by madhukard** [comment]
I am also curious on the above as well. I have updated my code to use ng2-material instead of Bootstrap - https://github.com/madhukard/angular2-jspm-seed

**Comment by losorio35** [comment]
+1

**Comment by justindujardin** [comment]
The readme is lacking, and I will try to update it when I have time.

As to motivations, I have been working with ng2 for a while on a [game project](https://github.com/justindujardin/angular2-rpg) and wanted to use the awesome [angular material](https://github.com/angular/material) components that I use at work with angular 1.x.

When I asked around, I was told that there was no official implementation of material components being worked on, so I decided to mash up the existing ng2 material work with angular material 1.x styles and examples.

I have followed the syntax of angular/material as closely as possible so that I can rely on the existing examples and documentation for most of what I'm building.  I understand that it could potentially conflict with an official implementation, but I haven't decided what to do about it yet.

I certainly don't intend for this project to be a placeholder, and would love to see it grow into something spectacular.  That being said, I'm only one person and have only so much free time outside of work to contribute. Google could probably pretty easily put a real team behind making what I've done irrelevant at any point.  I don't know what their plans are.

I will continue to work on this project as long as there is a need for it. I would love to have more people (like @jaroslavrehorka) contribute components, examples, and tests as well. 

I'm really glad to hear that people are finding it useful. :+1:

**Comment by NathanWalker** [comment]
You've done a fantastic job and I will try to contribute in the future.
Thanks for everything you've done here!

**Comment by shawnrmoss** [comment]
This is awesome!  Amazing work

**Comment by geelus** [comment]
This is definitely a great job. Congrats! 

One thing I noticed is that the difference in the syntax. For example the official implementation of a button is:
 <md-button>{{title1}}</md-button>
But yours is:
 <button md-button>{{title1}}</button>
is this is actually a difference or your could use it both ways?

Thanks,
Morteza

**Comment by justindujardin** [comment]
@geelus The first example you give will not work, you need to use the attribute specifier as in the examples in this repo.

This is a difference from the official angular/material components for angular1.x.  I tend to like specifying them this way.  I think that it makes it much easier for tools or browsers to understand the intent of your application.  That is, lots of algorithms know about what a `<button>` does in a page, where fewer would know what a custom element `<md-button>` does. It also allows the button directives to be simpler because you can have two of them (one to represent a button and another to represent an anchor).

**Comment by geelus** [comment]
Thanks for your explanation. It makes sense to me.

I have not used the official material design yet. If I use it the same way as yours, is it going to work?

Best Regards,
Morteza

**Comment by jaroslavrehorka** [comment]
If you mean by an official this [page](material.angularjs.org) then not exactly, because the official material design is for angular 1. Just follow examples on the official page and you will be fine, there are some differences but nothing really big. Regarding to design it should be same.

**Comment by geelus** [comment]
Alright got it. Thanks for your prompt response.

**Comment by ollwenjones** [comment]
If this project grows in community / features, is it inconceivable that google will incorporate parts into their ng2-material core?

**Comment by jaroslavrehorka** [comment]
who knows... =D maybe, but many of these are from official angular2 repo where are some basic components for material design in angular2 already done. And for example circle spinner is just rewritten from angular1 material to typescript, sass styles are almost 1:1 with original.

**Comment by ollwenjones** [comment]
makes sense the styles should be about 1:1 - unless there were breaking DOM changes due to the change to component-based architecture.

**Comment by DennisSmolek** [comment]
One issue is many of the ng1 stuff isn't needed anymore so some of the structures are different. If you try to stick with all ng1 styles/rules it becomes a bit of a pain. For example, there are a lot of "wrapper" elements, extra classes, and some other basic fluff that ng2 lets you clear right out.

**Comment by ollwenjones** [comment]
I haven't dug in yet. I was hoping the styles were more BEM -like and thus less dependent on the dom structure. The current ng1-material should still be a good starting point, or at least better than the Material Design Lite CSS that I was starting with before.  but you're right. We'll need to make sure we're writing good ng2, not just transcribing, of course.

**Comment by justindujardin** [comment]
Closing as I updated the README to talk about the purpose for this project. 

I think the best path forward is to plan for a migration to the official material2 implementation when it becomes more usable. 

I'll still work with the community to accept PRs and keep up to date with the latest angular2 beta builds.

**Comment by Gregcop1** [comment]
How is it now than ng-material2 is on alpha? Do contributors have to make their PR directly on ng-material2 ?
