### ISSUE TITLE
two way databinding is not working on md-input

### ISSUE THREAD

**Issue by eelwayadmin** [justindujardin/ng2-material#62]
In form_builder.html, two way data binding for input is not working
<input md-input ngControl="description" id="description" [(value)]="model.description">

In fact you should implements a valueChange in MdInput:
@Output('valueChange') _valueChanges:EventEmitter<string> = new EventEmitter();

**Comment by ollwenjones** [comment]
I've gotten wrapped around the axle on related things before. It doesn't seem like a `[(value)]="model.description"` binding really does what the cheat-sheet says it does. The form-builder example would work with just an `ngModel` instead of `value,` though I suppose the `@Output` would actually fix it inside the component.

**Comment by justindujardin** [comment]
@eelwayadmin thanks!

**Comment by fxck** [comment]
using [(value)] doesn't trigger validity check, thus making valid inputs invalid https://github.com/justindujardin/ng2-material/issues/100 which means you can't use `form.valid` etc...
